apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "olx-app.labels" . | nindent 4 }}
    app: olx-client
spec:
  selector:
    app: olx-client
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  type: ClusterIP