{{- if .Values.azureFrontDoor.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olx-website-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    {{- range $key, $value := .Values.azureFrontDoor.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.azureFrontDoor.hostname }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.service.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}