apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "olx-app.labels" . | nindent 4 }}
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
  type: ClusterIP