apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "olx-app.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        {{- include "olx-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.env.POSTGRES_USER }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.env.POSTGRES_HOST }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.env.POSTGRES_PORT | quote }}
        - name: PGDATA
          value: {{ .Values.postgres.env.PGDATA }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc