apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "olx-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.env.POSTGRES_PASSWORD }}