apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.database.name }}
    chart: {{ template "olx-website.chart" . }}
    release: {{ .Release.Name }}
data:
  POSTGRES_DB: {{ .Values.database.env.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.database.env.POSTGRES_USER }}
  POSTGRES_HOST: {{ .Values.database.env.POSTGRES_HOST }}
  POSTGRES_PORT: {{ .Values.database.env.POSTGRES_PORT | quote }}
  PGDATA: {{ .Values.database.env.PGDATA }}