apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.database.name }}
    chart: {{ template "olx-website.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: {{ .Values.database.name }}
        image: {{ .Values.database.image }}:{{ .Values.database.tag }}
        ports:
        - containerPort: {{ .Values.database.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.database.env.POSTGRES_USER }}
        - name: POSTGRES_HOST
          value: {{ .Values.database.env.POSTGRES_HOST }}
        - name: POSTGRES_PORT
          value: {{ .Values.database.env.POSTGRES_PORT | quote }}
        - name: PGDATA
          value: {{ .Values.database.env.PGDATA }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: {{ .Values.database.resources.requests.memory }}
            cpu: {{ .Values.database.resources.requests.cpu }}
          limits:
            memory: {{ .Values.database.resources.limits.memory }}
            cpu: {{ .Values.database.resources.limits.cpu }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        {{- if .Values.database.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.database.name }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}