apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.database.name }}
    chart: {{ template "olx-website.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.secret.POSTGRES_PASSWORD }}