services:
  web:
    profiles: ['web-only', 'full']
    image: 18_e_learn-master-web:latest
    container_name: web
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mssql
    networks:
      private-network:
        ipv4_address: 172.20.0.11
      bridge-network:

  mssql:
    profiles: ['sql-only', 'full']
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Qwerty-1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      private-network:
        ipv4_address: 172.20.0.10
          
networks:
  private-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
  bridge-network:
    driver: bridge

volumes:
  dataprotection-keys:
  mssql-data:
