services:
  web:
    profiles: ['web', 'full']
    image: 18_e_learn-master-web:latest
    container_name: web
    #restart: always
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mssql
    networks:
      app-network:
        aliases:
          - web.local

  mssql:
    profiles: ['sql-only', 'full']
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    #restart: always
    environment:
      SA_PASSWORD: "Qwerty-1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      app-network:
        aliases:
          - mssql.local

networks:
  app-network:
    driver: bridge

volumes:
  dataprotection-keys:
  mssql-data:
