services:
  web: 
    profiles: ['web-only', 'full']
    image: voutuk/18_e_learn-master-web:latest
    container_name: web
    #restart: unless-stopped #CHANEME: Uncomment this line
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #CHANEME: Change to Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes: #SECURITY: Data protection keys
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys:rw
    depends_on:
      mssql:
        condition: service_healthy
    healthcheck: #TASK: Use WAF
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      web-network:
        ipv4_address: 172.20.0.11

  mssql: 
    profiles: ['sql-only', 'full']
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    #restart: unless-stopped #CHANEME: Uncomment this line
    environment:
      SA_PASSWORD: "Qwerty-1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: #FIXME: Secure the volume
      - mssql-data:/var/opt/mssql:rw
      - ./mssql.conf:/var/opt/mssql/mssql.conf:rw
      - ./certificates/mssql.key:/var/opt/mssql/mssql.key:ro
      - ./certificates/mssql.pem:/var/opt/mssql/mssql.pem:ro
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Qwerty-1" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks: 
      web-network:
        ipv4_address: 172.20.0.10

networks: #TASK: Private network
  web-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes: #TASK: Backup the volume
  dataprotection-keys:
  mssql-data:
