# Default values for olx-website
namespace: gosell

backend:
  name: backend
  image: voutuk/olx-api
  tag: latest
  port: 8080
  service:
    port: 80
    targetPort: 8080
  env:
    ASPNETCORE_ENVIRONMENT: Production
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

frontend:
  name: frontend
  image: voutuk/olx-client
  tag: latest
  port: 80
  service:
    port: 80
    targetPort: 80
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  
database:
  name: postgres-service
  image: postgres
  tag: latest
  port: 5432
  service:
    port: 5432
    targetPort: 5432
  env:
    POSTGRES_DB: olxDb
    POSTGRES_USER: olxapi
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"
    PGDATA: /var/lib/postgresql/data/pgdata
  secret:
    POSTGRES_PASSWORD: KmRtVW50ZE9pZGQzZF8jV1RpNEI5Wm9acCVyU0RqNEltZHMwN2RqYyo= # Base64 encoded password
  persistence:
    enabled: true
    storageClass: ""
    size: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  replicas: 1

azureFrontDoor:
  enabled: true
  hostname: pluton.pp.ua
  annotations:
    # Azure Front Door specific annotations
    azure-frontdoor.io/frontend-endpoints: "fe-endpoint"
    azure-frontdoor.io/routing-rules: "rr-rule"
    azure-frontdoor.io/backend-pool: "bp-pool"