# Generated by Terraform on ${timestamp}
# Generated by user: ${user}

[main_inst]
main ansible_host=${main_ip} ansible_user=${admin_username}

[builders_inst]
%{ for index, ip in agent_ips ~}
agent${index} ansible_host=${ip} ansible_user=${admin_username}
%{ endfor ~}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/apps/azure_rsa