pipeline {
    agent any

    stages {
        stage('Build frontend') {
            steps {
                sh 'docker build -t olx-client ./OLX_Dyplom_ADM/OLX.Frontend'
            }
        }

        stage('Build backend') {
            steps {
                sh 'docker build -t olx-asp-api ./OLX_Dyplom_ADM/OLX.API'
            }
        }

        stage('Docker Compose Up') {
            steps {
                sh 'docker compose -f ./OLX_Dyplom_ADM/docker-compose.yml up -d'
            }
        }

        stage('Show public IP of the host') {
            steps {
                script {
                    echo "Public IP of this host:"
                    sh 'curl -s ifconfig.me'
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed. Please check the logs."
        }
    }
}