apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "onix-app.labels" . | nindent 4 }}
    app: onix-api
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: onix-api
  template:
    metadata:
      labels:
        app: onix-api
        {{- include "onix-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: onix-api
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}