{{- if .Values.cloudflare.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "onix-app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cloudflare.certificate }}
  tls.key: {{ .Values.cloudflare.privateKey }}
{{- end }}