{{- if and .Values.namespace .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "onix-app.labels" . | nindent 4 }}
{{- end }}