---
# Playbook created by: voutuk
# Creation date (UTC): 2025-01-27 12:17:25
- name: Setup Jenkins Agent with Docker and Swap
  hosts: builders_inst
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present

    # Swap Space Configuration
    - name: Check if swap file exists
      stat:
        path: "{{ swap_file_path }}"
      register: swap_file_check

    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_size_mb }}
      when: not swap_file_check.stat.exists

    - name: Set swap file permissions
      file:
        path: "{{ swap_file_path }}"
        mode: '0600'
      when: not swap_file_check.stat.exists

    - name: Make swap
      command: mkswap {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Enable swap
      command: swapon {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ swap_file_path }} none swap sw 0 0"
        state: present
      when: not swap_file_check.stat.exists

    # Docker Installation and Configuration
    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    # Docker permissions configuration
    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
        
    - name: Create docker configuration directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon
      copy:
        content: |
          {
            "live-restore": true,
            "group": "docker"
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart Docker

    - name: Create systemd override directory for docker
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

    - name: Configure Docker socket permissions
      copy:
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: '0644'
      notify:
        - Daemon reload
        - Restart Docker

    # Using group permissions instead of 0666 permissions
    - name: Set appropriate ownership and permissions on Docker socket
      file:
        path: /var/run/docker.sock
        group: docker
        mode: '0660'
      notify: Restart Docker

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
  
  handlers:
    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart Docker
      service:
        name: docker
        state: restarted