---
- hosts: main_inst
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Perform restic backup of Jenkins home
      shell: |
        restic -r "{{ RESTIC_REPOSITORY }}" backup /home/ubuntu/jenkins_home
      environment:
        RESTIC_PASSWORD: "{{ RESTIC_PASSWORD }}"
        AZURE_ACCOUNT_NAME: "{{ AZURE_ACCOUNT_NAME }}"
        AZURE_ACCOUNT_KEY: "{{ AZURE_ACCOUNT_KEY }}"
      register: backup_output
      failed_when: backup_output.rc not in [0]
      changed_when: backup_output.rc == 0

    - name: Debug backup output
      debug:
        var: backup_output