# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
  features {}
  subscription_id = var.azure_subscription_id
  client_id       = data.doppler_secrets.az-creds.map.CLIENT_ID
  client_secret   = data.doppler_secrets.az-creds.map.CLIENT_SECRET
  tenant_id       = data.doppler_secrets.az-creds.map.TENANT_ID
}

provider "doppler" {
  doppler_token = var.doppler_token
}

provider "azapi" {
  subscription_id = var.azure_subscription_id
  client_id       = data.doppler_secrets.az-creds.map.CLIENT_ID
  client_secret   = data.doppler_secrets.az-creds.map.CLIENT_SECRET
  tenant_id       = data.doppler_secrets.az-creds.map.TENANT_ID
}

# Отримання даних про існуючий AKS кластер
data "azurerm_kubernetes_cluster" "existing" {
  name                = var.aks_name
  resource_group_name = var.aks_location
}

# Конфігурація Kubernetes провайдера
provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.existing.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.cluster_ca_certificate)
}

# Конфігурація Helm провайдера
provider "helm" {
  kubernetes {
    host                   = data.azurerm_kubernetes_cluster.existing.kube_config.0.host
    client_certificate     = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.client_certificate)
    client_key             = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.existing.kube_config.0.cluster_ca_certificate)
  }
}

provider "time" {}
provider "random" {}
provider "local" {}
