apiVersion: apps/v1
kind: Deployment
metadata:
  name: olx-client
  namespace: gosell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olx-client
  template:
    metadata:
      labels:
        app: olx-client
    spec:
      nodeSelector:
        role: frontend
      containers:
        - name: olx-client-container
          image: voutuk/olx-client:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: olx-client-service
  namespace: gosell
spec:
  type: ClusterIP
  selector:
    app: olx-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80