apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gosell-ingress
  namespace: gosell
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /hub
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080