---
# Playbook created by: voutuk
# Creation date (UTC): 2025-01-27 12:17:25
- name: Setup Jenkins Agent with Docker and Swap
  hosts: builders_inst
  become: yes
  vars:
    java_package: openjdk-17-jre-headless
    jenkins_agent_workdir: /home/azureuser
    jenkins_master_url: "http://jen.pluton.pp.ua/jenkins"
    jenkins_agent_name: "Qwertyu"
    jenkins_agent_user: azureuser
    swap_file_path: /swapfile
    swap_size_mb: 2048

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present

    # Swap Space Configuration
    - name: Check if swap file exists
      stat:
        path: "{{ swap_file_path }}"
      register: swap_file_check

    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_size_mb }}
      when: not swap_file_check.stat.exists

    - name: Set swap file permissions
      file:
        path: "{{ swap_file_path }}"
        mode: '0600'
      when: not swap_file_check.stat.exists

    - name: Make swap
      command: mkswap {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Enable swap
      command: swapon {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ swap_file_path }} none swap sw 0 0"
        state: present
      when: not swap_file_check.stat.exists

    # Docker Installation and Configuration
    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    # Docker permissions configuration
    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add Jenkins agent user to docker group
      user:
        name: "{{ jenkins_agent_user }}"
        groups: docker
        append: yes

    - name: Create docker configuration directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon
      copy:
        content: |
          {
            "live-restore": true,
            "group": "docker"
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart Docker

    - name: Create systemd override directory for docker
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

    - name: Configure Docker socket permissions
      copy:
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd
          SocketMode=0666
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: '0644'
      notify:
        - Daemon reload
        - Restart Docker

    - name: Set permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'
      notify: Restart Docker

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Jenkins Agent Setup
    - name: Create Jenkins agent directory
      file:
        path: "{{ jenkins_agent_workdir }}"
        state: directory
        owner: "{{ jenkins_agent_user }}"
        group: "{{ jenkins_agent_user }}"
        mode: '0755'

    - name: Download Jenkins agent JAR
      get_url:
        url: "{{ jenkins_master_url }}/jnlpJars/agent.jar"
        dest: "{{ jenkins_agent_workdir }}/agent.jar"
        mode: '0755'
        owner: "{{ jenkins_agent_user }}"
        group: "{{ jenkins_agent_user }}"

    - name: Create systemd service file
      template:
        src: jenkins-agent.service.j2
        dest: /etc/systemd/system/jenkins-agent.service
        mode: '0644'
      notify: Restart Jenkins agent

  handlers:
    - name: Restart Jenkins agent
      systemd:
        name: jenkins-agent
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted