---
- hosts: all
  become: yes
  tasks:
    # Automatic Updates Configuration
    - name: Install unattended-upgrades
      apt:
        name: 
          - unattended-upgrades
          - apt-listchanges
        state: present

    - name: Enable automatic updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::AutocleanInterval "7";

    - name: Configure unattended-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}";
              "${distro_id}:${distro_codename}-security";
              "${distro_id}ESMApps:${distro_codename}-apps-security";
              "${distro_id}ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::AutoFixInterruptedDpkg "true";
          Unattended-Upgrade::MinimalSteps "true";
          Unattended-Upgrade::InstallOnShutdown "false";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Automatic-Reboot "false";

    # Docker Installation (remains unchanged)
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    # Cloudflared Installation and Setup
    - name: Download Cloudflared package
      get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        dest: /tmp/cloudflared.deb
        mode: '0644'

    - name: Install Cloudflared
      apt:
        deb: /tmp/cloudflared.deb
        state: present

    - name: Create Cloudflared directory
      file:
        path: /etc/cloudflared
        state: directory
        mode: '0755'

    - name: Install Cloudflared service
      command: cloudflared service install "{{ cloudflared_token }}"
      args:
        creates: /etc/systemd/system/cloudflared.service

    - name: Enable and start Cloudflared service
      systemd:
        name: cloudflared
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Clean up Cloudflared package
      file:
        path: /tmp/cloudflared.deb
        state: absent

    # Verify installations
    - name: Check Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        var: docker_version.stdout