apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-pluton-dns-cert
  namespace: gosell
spec:
  secretName: app-pluton-tls
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
  commonName: app.pluton.pp.ua
  dnsNames:
  - app.pluton.pp.ua