apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: voutuk@icloud.com
    privateKeySecretRef:
      name: letsencrypt-dns-prod-key
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: gosell-aks-cluster
          subscriptionID: 3eba8433-8aaf-40ef-9be5-87b8edefec97
          hostedZoneName: pluton.pp.ua
          tenantID: "ae561515-9385-4483-bef2-aec8255d3705"  # <-- Додайте цей рядок з вашим Azure Tenant ID
          environment: AzurePublicCloud
          clientID: ZDQ0NzM5ZmEtZTY0YS00YTZkLTk0NTYtZWU2Y2I0YzAwNjI4
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
      selector:
        dnsZones:
        - "pluton.pp.ua"