apiVersion: apps/v1
kind: Deployment
metadata:
  name: olx-backend
  namespace: gosell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olx-backend
  template:
    metadata:
      labels:
        app: olx-backend
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: olx-api
          image: voutuk/olx-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: "3Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          volumeMounts:
            - name: images
              mountPath: /app/uploading
      volumes:
        - name: images
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: olx-backend-service
  namespace: gosell
spec:
  type: ClusterIP
  selector:
    app: olx-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080