apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olx-ingress
  namespace: gosell
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/api/Category/get"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: olx-backend-service
            port:
              number: 80
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: olx-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: olx-client-service
            port:
              number: 80