apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    chart: {{ template "olx-website.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}