name: Kubernetes Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  kubernetes-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'infra/Kube/yarn.lock'

      - name: Install dependencies
        run: cd infra/Kube && yarn install

      - name: Set up Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Connect to Doppler project
        run: doppler setup --no-prompt --token ${{ secrets.DOPPLER_TOKEN }}
        
      - name: Pre-deployment setup
        run: cd infra/Kube && yarn run pre
        
      - name: Deploy to Kubernetes
        run: cd infra/Kube && yarn run deploy
