name: Terraform Deployment
on:
  workflow_dispatch:
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.8'

      - name: Verify Terraform installation
        run: terraform --version

      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=0.73.11
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          which terragrunt && terragrunt --version

      - name: Set up Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Connect to Doppler project
        run: doppler setup --no-interactive --token ${{ secrets.DOPPLER_TOKEN }} --project "az" --config dev

      - name: Initialize Terraform
        run: cd infra/Terraform && terraform init

      - name: Pre-deployment setup
        continue-on-error: true
        run: cd infra/Terraform && doppler run -- terraform apply -target=module.sa -auto-approve

      - name: Initialize Terragrunt
        run: cd infra/Terraform && doppler run -- terragrunt init --non-interactive

      - name: Plan Terraform changes
        run: cd infra/Terraform && doppler run -- terragrunt plan

      - name: Apply Terraform changes
        run: cd infra/Terraform && doppler run -- terragrunt apply -auto-approve -target=module.ci -target=module.aks -target=module.network -target=module.acr