name: Terraform Deployment
on:
  workflow_dispatch:

env:
  tf_version: '1.11.2'
  tg_version: '0.73.11'
  working_dir: 'infra/Terraform'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Initialize Terraform
        run: cd infra/Terraform && terraform init

      - name: Pre-deployment setup
        continue-on-error: true
        run: cd infra/Terraform && doppler run -- terraform apply -target=module.sa -auto-approve

      - name: Initialize Terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir:     ${{ env.working_dir }}
          tg_command: 'init --non-interactive'

      - name: Plan Terraform changes
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir:     ${{ env.working_dir }}
          tg_command: 'plan --non-interactive'

      - name: Apply Terraform changes
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir:     ${{ env.working_dir }}
          tg_command: 'apply -auto-approve -target=module.ci -target=module.aks -target=module.network -target=module.acr --non-interactive'