name: Terraform Deployment
on:
  workflow_dispatch:
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'
      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=0.53.1
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version
      - name: Set up Doppler CLI
        uses: dopplerhq/cli-action@v2
      - name: Connect to Doppler project
        run: doppler setup --no-interactive --token ${{ secrets.DOPPLER_TOKEN }} --project "az" --config dev
       
      - name: Pre-deployment setup
        run: cd infra/Terraform && terraform init && doppler run -- terraform apply -target=module.sa -auto-approve
       
      - name: Initialize Terraform
        run: cd infra/Terraform && doppler run -- terragrunt init --terragrunt-non-interactive
       
      - name: Apply Terraform changes
        run: cd infra/Terraform && doppler run -- terragrunt apply -auto-approve -target=module.ci -target=module.aks -target=module.network -target=module.acr