name: 'Terraform Deployment'

on:
  workflow_dispatch:

env:
  TF_VAR_doppler_token: ${{ secrets.TF_VAR_doppler_token }}
  WORKING_DIR: ./OLX_Dyplom_ADM/Tf3.0

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform init

    - name: Terraform validate
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform plan
      
    - name: Deploy Resource Group
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.resource_group -auto-approve

    - name: Deploy NSG
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.create_nsg -auto-approve

    - name: Deploy Main Instance
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.main_instance -auto-approve

    - name: Deploy Build Agent Instance
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.build_agent_instance -auto-approve

    - name: Deploy AKS Cluster
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.aks_cluster -auto-approve
    
    - name: Generate Ansible Inventory
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -target=module.ansible_inventory -auto-approve