name: Terraform Deployment
on:
  workflow_dispatch:

env:
  tf_version: '1.11.2'
  tg_version: '0.73.11'
  working_dir: 'infra/Terraform'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir:     ${{ env.working_dir }}
          tg_command: 'plan'

      - name: Set up Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Connect to Doppler project
        run: doppler setup --no-interactive --token ${{ secrets.DOPPLER_TOKEN }} --project "az" --config dev

      - name: Initialize Terraform
        run: cd infra/Terraform && terraform init

      - name: Pre-deployment setup
        continue-on-error: true
        run: cd infra/Terraform && doppler run -- terraform apply -target=module.sa -auto-approve

      - name: Create terraform-bin symlink
        run: |
          sudo ln -sf $(which terraform) /usr/local/bin/terraform-bin
          ls -la /usr/local/bin/terraform-bin

      - name: Initialize Terragrunt
        run: cd infra/Terraform && doppler run -- terragrunt init --non-interactive

      - name: Plan Terraform changes
        run: cd infra/Terraform && doppler run -- terragrunt plan

      - name: Apply Terraform changes
        run: cd infra/Terraform && doppler run -- terragrunt apply -auto-approve -target=module.ci -target=module.aks -target=module.network -target=module.acr